apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-dev-ns-cluster-admin
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
