apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-view-dev-ns
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view