apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccount:prometheus
    namespace: prometheus
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: pod-reader