apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stub-conf
data:
  stub.conf: |
    server {
      listen       80;
      server_name  localhost;
      location /basic_status {
        stub_status;
      }
    }