apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  initContainers:
    - name: init-web
      image: busybox:latest
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - mountPath: /app
          name: app
  containers: # Описание контейнеров внутри Pod
  - name: web # Название контейнера
    image: avecake/mynginx:1 # Образ из которого создается контейнер
    volumeMounts:
      - mountPath: /app
        name: app
  volumes:
    - name: app
      emptyDir: {}